WIP: Coremem cleanup
lowRISC/minion_subsystem pull request #5
Opened 2017-08-11 08:30 UTC by nchronas

Removed code coremem due to unreached states (WRITE_DATA, WRITE_ADDR) because of constant assignment of aw_ready_i, ar_ready_i and w_ready_i. The states could further reduced from READ_WAIT, WRITE_WAIT to WAIT but I left it that way because I think code is more readable.

I will need to test the changes in an Arty board.

2017-08-14 12:48 UTC, nchronas commented
Tested with arty and an example program running blinking LEDs and transmitted a string from the UART.

More testing should be done with a nexus board and the rocket core.

2017-08-22 14:38 UTC, jrrk requested changes
Please patch as follows:

-   enum         logic [2:0] { IDLE, READ_WAIT, WRITE_WAIT } CS, NS;
+   enum         logic [2:0] { IDLE, READ_WAIT, WRITE_DATA, WRITE_ADDR, WRITE_WAIT } CS, NS;

This will ensure that the function and logic coding is identical to before. (Avoiding having to restest everything).

2017-08-22 15:30 UTC, nchronas commented
@jrrk required changes were made in a new commit.

2017-08-22 15:32 UTC, jrrk approved these changes

2017-08-22 15:34 UTC, merged